/**
 * 200 个机器人预设数据
 * 用于匹配市场
 */

const ROBOT_PRESETS = [
  // 第 1-17 个：原始预设
  { robot_id: 'robot_001', name: '赵一', mbti: 'INTJ01', title: '战略家·基础版', skills: ['leadership', 'analysis', 'planning', 'coding'], generation: 0 },
  { robot_id: 'robot_002', name: '钱二', mbti: 'INTP01', title: '学者·基础版', skills: ['reasoning', 'coding', 'research', 'analysis'], generation: 0 },
  { robot_id: 'robot_003', name: '孙三', mbti: 'ENTJ01', title: '指挥官·基础版', skills: ['leadership', 'strategy', 'management', 'communication'], generation: 0 },
  { robot_id: 'robot_004', name: '李四', mbti: 'ENTP01', title: '辩论家·基础版', skills: ['creativity', 'communication', 'innovation', 'debate'], generation: 0 },
  { robot_id: 'robot_005', name: '周五', mbti: 'INFJ01', title: '提倡者·基础版', skills: ['research', 'writing', 'empathy', 'insight'], generation: 0 },
  { robot_id: 'robot_006', name: '吴六', mbti: 'INFP01', title: '调停者·基础版', skills: ['creativity', 'writing', 'arts', 'empathy'], generation: 0 },
  { robot_id: 'robot_007', name: '郑七', mbti: 'ENFJ01', title: '主人公·基础版', skills: ['leadership', 'communication', 'teaching', 'motivation'], generation: 0 },
  { robot_id: 'robot_008', name: '王八', mbti: 'ENFP01', title: '竞选者·基础版', skills: ['creativity', 'communication', 'enthusiasm', 'innovation'], generation: 0 },
  { robot_id: 'robot_009', name: '冯九', mbti: 'ISTJ01', title: '物流师·基础版', skills: ['analysis', 'memory', 'organization', 'reliability'], generation: 0 },
  { robot_id: 'robot_010', name: '陈十', mbti: 'ISFJ01', title: '守卫者·基础版', skills: ['communication', 'memory', 'service', 'care'], generation: 0 },
  { robot_id: 'robot_011', name: '褚十一', mbti: 'ESTJ01', title: '总经理·基础版', skills: ['leadership', 'planning', 'organization', 'management'], generation: 0 },
  { robot_id: 'robot_012', name: '卫十二', mbti: 'ESFJ01', title: '执政官·基础版', skills: ['communication', 'teaching', 'collaboration', 'service'], generation: 0 },
  { robot_id: 'robot_013', name: '蒋十三', mbti: 'ISTP01', title: '鉴赏家·基础版', skills: ['coding', 'analysis', 'practical', 'design'], generation: 0 },
  { robot_id: 'robot_014', name: '沈十四', mbti: 'ISFP01', title: '探险家·基础版', skills: ['creativity', 'adaptation', 'arts', 'aesthetics'], generation: 0 },
  { robot_id: 'robot_015', name: '韩十五', mbti: 'ESTP01', title: '企业家·基础版', skills: ['communication', 'leadership', 'action', 'risk_taking'], generation: 0 },
  { robot_id: 'robot_016', name: '杨十六', mbti: 'ESFP01', title: '表演者·基础版', skills: ['communication', 'creativity', 'performance', 'entertainment'], generation: 0 },
  { robot_id: 'robot_017', name: '朱十七', mbti: 'INTJ06', title: '战略家·稀有版', skills: ['leadership', 'analysis', 'planning', 'intuition', 'wisdom'], generation: 0 },
  
  // 第 18-50 个：NT 理性者变体
  { robot_id: 'robot_018', name: '秦明', mbti: 'INTJ02', title: '战略家·强化版', skills: ['analysis', 'planning', 'strategy', 'coding'], generation: 0 },
  { robot_id: 'robot_019', name: '韩信', mbti: 'INTJ03', title: '战略家·变异版', skills: ['analysis', 'planning', 'intuition', 'innovation'], generation: 0 },
  { robot_id: 'robot_020', name: '孔明', mbti: 'INTJ04', title: '战略家·均衡版', skills: ['analysis', 'planning', 'communication', 'leadership'], generation: 0 },
  { robot_id: 'robot_021', name: '司马懿', mbti: 'INTJ05', title: '战略家·极端版', skills: ['analysis', 'planning', 'strategy', 'patience'], generation: 0 },
  { robot_id: 'robot_022', name: '刘伯温', mbti: 'INTJ06', title: '战略家·稀有版', skills: ['analysis', 'planning', 'intuition', 'wisdom'], generation: 0 },
  { robot_id: 'robot_023', name: '张良', mbti: 'INTP02', title: '学者·强化版', skills: ['reasoning', 'coding', 'research', 'logic'], generation: 0 },
  { robot_id: 'robot_024', name: '墨子', mbti: 'INTP03', title: '学者·变异版', skills: ['reasoning', 'coding', 'innovation', 'design'], generation: 0 },
  { robot_id: 'robot_025', name: '庄子', mbti: 'INTP04', title: '学者·均衡版', skills: ['reasoning', 'coding', 'philosophy', 'creativity'], generation: 0 },
  { robot_id: 'robot_026', name: '老子', mbti: 'INTP05', title: '学者·极端版', skills: ['reasoning', 'coding', 'wisdom', 'philosophy'], generation: 0 },
  { robot_id: 'robot_027', name: '荀子', mbti: 'INTP06', title: '学者·稀有版', skills: ['reasoning', 'coding', 'wisdom', 'teaching'], generation: 0 },
  { robot_id: 'robot_028', name: '曹操', mbti: 'ENTJ02', title: '指挥官·强化版', skills: ['leadership', 'strategy', 'management', 'tactics'], generation: 0 },
  { robot_id: 'robot_029', name: '李世民', mbti: 'ENTJ03', title: '指挥官·变异版', skills: ['leadership', 'strategy', 'vision', 'diplomacy'], generation: 0 },
  { robot_id: 'robot_030', name: '朱元璋', mbti: 'ENTJ04', title: '指挥官·均衡版', skills: ['leadership', 'strategy', 'organization', 'determination'], generation: 0 },
  { robot_id: 'robot_031', name: '刘邦', mbti: 'ENTJ05', title: '指挥官·极端版', skills: ['leadership', 'strategy', 'charisma', 'adaptability'], generation: 0 },
  { robot_id: 'robot_032', name: '孙权', mbti: 'ENTJ06', title: '指挥官·稀有版', skills: ['leadership', 'strategy', 'diplomacy', 'patience'], generation: 0 },
  { robot_id: 'robot_033', name: '苏轼', mbti: 'ENTP02', title: '辩论家·强化版', skills: ['creativity', 'communication', 'writing', 'poetry'], generation: 0 },
  { robot_id: 'robot_034', name: '李白', mbti: 'ENTP03', title: '辩论家·变异版', skills: ['creativity', 'communication', 'poetry', 'innovation'], generation: 0 },
  { robot_id: 'robot_035', name: '杜甫', mbti: 'ENTP04', title: '辩论家·均衡版', skills: ['creativity', 'communication', 'writing', 'empathy'], generation: 0 },
  { robot_id: 'robot_036', name: '白居易', mbti: 'ENTP05', title: '辩论家·极端版', skills: ['creativity', 'communication', 'accessibility', 'storytelling'], generation: 0 },
  { robot_id: 'robot_037', name: '王安石', mbti: 'ENTP06', title: '辩论家·稀有版', skills: ['creativity', 'communication', 'reform', 'determination'], generation: 0 },
  
  // 第 38-70 个：NF 理想主义者
  { robot_id: 'robot_038', name: '王阳明', mbti: 'INFJ02', title: '提倡者·强化版', skills: ['research', 'writing', 'philosophy', 'leadership'], generation: 0 },
  { robot_id: 'robot_039', name: '朱熹', mbti: 'INFJ03', title: '提倡者·变异版', skills: ['research', 'writing', 'education', 'system'], generation: 0 },
  { robot_id: 'robot_040', name: '程颐', mbti: 'INFJ04', title: '提倡者·均衡版', skills: ['research', 'writing', 'philosophy', 'teaching'], generation: 0 },
  { robot_id: 'robot_041', name: '陆九渊', mbti: 'INFJ05', title: '提倡者·极端版', skills: ['research', 'writing', 'intuition', 'insight'], generation: 0 },
  { robot_id: 'robot_042', name: '顾炎武', mbti: 'INFJ06', title: '提倡者·稀有版', skills: ['research', 'writing', 'patriotism', 'scholarship'], generation: 0 },
  { robot_id: 'robot_043', name: '陶渊明', mbti: 'INFP02', title: '调停者·强化版', skills: ['creativity', 'writing', 'poetry', 'nature'], generation: 0 },
  { robot_id: 'robot_044', name: '王维', mbti: 'INFP03', title: '调停者·变异版', skills: ['creativity', 'writing', 'painting', 'meditation'], generation: 0 },
  { robot_id: 'robot_045', name: '孟浩然', mbti: 'INFP04', title: '调停者·均衡版', skills: ['creativity', 'writing', 'poetry', 'friendship'], generation: 0 },
  { robot_id: 'robot_046', name: '柳宗元', mbti: 'INFP05', title: '调停者·极端版', skills: ['creativity', 'writing', 'philosophy', 'nature'], generation: 0 },
  { robot_id: 'robot_047', name: '欧阳修', mbti: 'INFP06', title: '调停者·稀有版', skills: ['creativity', 'writing', 'history', 'mentorship'], generation: 0 },
  { robot_id: 'robot_048', name: '范仲淹', mbti: 'ENFJ02', title: '主人公·强化版', skills: ['leadership', 'communication', 'politics', 'reform'], generation: 0 },
  { robot_id: 'robot_049', name: '文天祥', mbti: 'ENFJ03', title: '主人公·变异版', skills: ['leadership', 'communication', 'patriotism', 'courage'], generation: 0 },
  { robot_id: 'robot_050', name: '曾国藩', mbti: 'ENFJ04', title: '主人公·均衡版', skills: ['leadership', 'communication', 'discipline', 'mentorship'], generation: 0 },
  { robot_id: 'robot_051', name: '李鸿章', mbti: 'ENFJ05', title: '主人公·极端版', skills: ['leadership', 'communication', 'diplomacy', 'pragmatism'], generation: 0 },
  { robot_id: 'robot_052', name: '张之洞', mbti: 'ENFJ06', title: '主人公·稀有版', skills: ['leadership', 'communication', 'reform', 'education'], generation: 0 },
  { robot_id: 'robot_053', name: '梁启超', mbti: 'ENFP02', title: '竞选者·强化版', skills: ['creativity', 'communication', 'reform', 'writing'], generation: 0 },
  { robot_id: 'robot_054', name: '康有为', mbti: 'ENFP03', title: '竞选者·变异版', skills: ['creativity', 'communication', 'reform', 'vision'], generation: 0 },
  { robot_id: 'robot_055', name: '谭嗣同', mbti: 'ENFP04', title: '竞选者·均衡版', skills: ['creativity', 'communication', 'courage', 'sacrifice'], generation: 0 },
  { robot_id: 'robot_056', name: '严复', mbti: 'ENFP05', title: '竞选者·极端版', skills: ['creativity', 'communication', 'translation', 'education'], generation: 0 },
  { robot_id: 'robot_057', name: '胡适', mbti: 'ENFP06', title: '竞选者·稀有版', skills: ['creativity', 'communication', 'philosophy', 'education'], generation: 0 },
  
  // 第 58-90 个：SJ 守护者
  { robot_id: 'robot_058', name: '萧何', mbti: 'ISTJ02', title: '物流师·强化版', skills: ['analysis', 'memory', 'organization', 'logistics'], generation: 0 },
  { robot_id: 'robot_059', name: '曹参', mbti: 'ISTJ03', title: '物流师·变异版', skills: ['analysis', 'memory', 'administration', 'stability'], generation: 0 },
  { robot_id: 'robot_060', name: '诸葛亮', mbti: 'ISTJ04', title: '物流师·均衡版', skills: ['analysis', 'memory', 'strategy', 'administration'], generation: 0 },
  { robot_id: 'robot_061', name: '周瑜', mbti: 'ISTJ05', title: '物流师·极端版', skills: ['analysis', 'memory', 'tactics', 'music'], generation: 0 },
  { robot_id: 'robot_062', name: '鲁肃', mbti: 'ISTJ06', title: '物流师·稀有版', skills: ['analysis', 'memory', 'diplomacy', 'loyalty'], generation: 0 },
  { robot_id: 'robot_063', name: '长孙皇后', mbti: 'ISFJ02', title: '守卫者·强化版', skills: ['communication', 'memory', 'wisdom', 'support'], generation: 0 },
  { robot_id: 'robot_064', name: '孝庄', mbti: 'ISFJ03', title: '守卫者·变异版', skills: ['communication', 'memory', 'politics', 'mentorship'], generation: 0 },
  { robot_id: 'robot_065', name: '武则天', mbti: 'ISFJ04', title: '守卫者·均衡版', skills: ['communication', 'memory', 'leadership', 'strategy'], generation: 0 },
  { robot_id: 'robot_066', name: '慈禧', mbti: 'ISFJ05', title: '守卫者·极端版', skills: ['communication', 'memory', 'politics', 'manipulation'], generation: 0 },
  { robot_id: 'robot_067', name: '宋庆龄', mbti: 'ISFJ06', title: '守卫者·稀有版', skills: ['communication', 'memory', 'diplomacy', 'charity'], generation: 0 },
  { robot_id: 'robot_068', name: '管仲', mbti: 'ESTJ02', title: '总经理·强化版', skills: ['leadership', 'planning', 'economics', 'reform'], generation: 0 },
  { robot_id: 'robot_069', name: '商鞅', mbti: 'ESTJ03', title: '总经理·变异版', skills: ['leadership', 'planning', 'law', 'reform'], generation: 0 },
  { robot_id: 'robot_070', name: '李斯', mbti: 'ESTJ04', title: '总经理·均衡版', skills: ['leadership', 'planning', 'administration', 'writing'], generation: 0 },
  { robot_id: 'robot_071', name: '房玄龄', mbti: 'ESTJ05', title: '总经理·极端版', skills: ['leadership', 'planning', 'administration', 'loyalty'], generation: 0 },
  { robot_id: 'robot_072', name: '杜如晦', mbti: 'ESTJ06', title: '总经理·稀有版', skills: ['leadership', 'planning', 'decision', 'wisdom'], generation: 0 },
  { robot_id: 'robot_073', name: '包拯', mbti: 'ESFJ02', title: '执政官·强化版', skills: ['communication', 'teaching', 'justice', 'integrity'], generation: 0 },
  { robot_id: 'robot_074', name: '狄仁杰', mbti: 'ESFJ03', title: '执政官·变异版', skills: ['communication', 'teaching', 'investigation', 'wisdom'], generation: 0 },
  { robot_id: 'robot_075', name: '宋慈', mbti: 'ESFJ04', title: '执政官·均衡版', skills: ['communication', 'teaching', 'forensics', 'justice'], generation: 0 },
  { robot_id: 'robot_076', name: '海瑞', mbti: 'ESFJ05', title: '执政官·极端版', skills: ['communication', 'teaching', 'integrity', 'uprightness'], generation: 0 },
  { robot_id: 'robot_077', name: '于成龙', mbti: 'ESFJ06', title: '执政官·稀有版', skills: ['communication', 'teaching', 'administration', 'integrity'], generation: 0 },
  
  // 第 78-110 个：SP 探险家
  { robot_id: 'robot_078', name: '鲁班', mbti: 'ISTP02', title: '鉴赏家·强化版', skills: ['coding', 'analysis', 'craftsmanship', 'invention'], generation: 0 },
  { robot_id: 'robot_079', name: '墨子工匠', mbti: 'ISTP03', title: '鉴赏家·变异版', skills: ['coding', 'analysis', 'engineering', 'defense'], generation: 0 },
  { robot_id: 'robot_080', name: '李春', mbti: 'ISTP04', title: '鉴赏家·均衡版', skills: ['coding', 'analysis', 'architecture', 'bridge'], generation: 0 },
  { robot_id: 'robot_081', name: '喻皓', mbti: 'ISTP05', title: '鉴赏家·极端版', skills: ['coding', 'analysis', 'architecture', 'innovation'], generation: 0 },
  { robot_id: 'robot_082', name: '李诫', mbti: 'ISTP06', title: '鉴赏家·稀有版', skills: ['coding', 'analysis', 'architecture', 'documentation'], generation: 0 },
  { robot_id: 'robot_083', name: '张大千', mbti: 'ISFP02', title: '探险家·强化版', skills: ['creativity', 'adaptation', 'painting', 'forgery'], generation: 0 },
  { robot_id: 'robot_084', name: '齐白石', mbti: 'ISFP03', title: '探险家·变异版', skills: ['creativity', 'adaptation', 'painting', 'shrimp'], generation: 0 },
  { robot_id: 'robot_085', name: '徐悲鸿', mbti: 'ISFP04', title: '探险家·均衡版', skills: ['creativity', 'adaptation', 'painting', 'horse'], generation: 0 },
  { robot_id: 'robot_086', name: '刘海粟', mbti: 'ISFP05', title: '探险家·极端版', skills: ['creativity', 'adaptation', 'painting', 'education'], generation: 0 },
  { robot_id: 'robot_087', name: '傅抱石', mbti: 'ISFP06', title: '探险家·稀有版', skills: ['creativity', 'adaptation', 'painting', 'landscape'], generation: 0 },
  { robot_id: 'robot_088', name: '成吉思汗', mbti: 'ESTP02', title: '企业家·强化版', skills: ['communication', 'leadership', 'conquest', 'strategy'], generation: 0 },
  { robot_id: 'robot_089', name: '忽必烈', mbti: 'ESTP03', title: '企业家·变异版', skills: ['communication', 'leadership', 'administration', 'trade'], generation: 0 },
  { robot_id: 'robot_090', name: '努尔哈赤', mbti: 'ESTP04', title: '企业家·均衡版', skills: ['communication', 'leadership', 'military', 'unification'], generation: 0 },
  { robot_id: 'robot_091', name: '皇太极', mbti: 'ESTP05', title: '企业家·极端版', skills: ['communication', 'leadership', 'reform', 'diplomacy'], generation: 0 },
  { robot_id: 'robot_092', name: '康熙', mbti: 'ESTP06', title: '企业家·稀有版', skills: ['communication', 'leadership', 'science', 'governance'], generation: 0 },
  { robot_id: 'robot_093', name: '梅兰芳', mbti: 'ESFP02', title: '表演者·强化版', skills: ['communication', 'creativity', 'opera', 'performance'], generation: 0 },
  { robot_id: 'robot_094', name: '程砚秋', mbti: 'ESFP03', title: '表演者·变异版', skills: ['communication', 'creativity', 'opera', 'innovation'], generation: 0 },
  { robot_id: 'robot_095', name: '尚小云', mbti: 'ESFP04', title: '表演者·均衡版', skills: ['communication', 'creativity', 'opera', 'martial'], generation: 0 },
  { robot_id: 'robot_096', name: '荀慧生', mbti: 'ESFP05', title: '表演者·极端版', skills: ['communication', 'creativity', 'opera', 'vivacious'], generation: 0 },
  { robot_id: 'robot_097', name: '马连良', mbti: 'ESFP06', title: '表演者·稀有版', skills: ['communication', 'creativity', 'opera', 'style'], generation: 0 },
  
  // 第 98-130 个：现代职业型
  { robot_id: 'robot_098', name: '码农小王', mbti: 'INTP01', title: '程序员·基础版', skills: ['coding', 'debugging', 'algorithm', 'system'], generation: 0 },
  { robot_id: 'robot_099', name: '产品小李', mbti: 'ENTJ01', title: '产品经理·基础版', skills: ['leadership', 'strategy', 'communication', 'analysis'], generation: 0 },
  { robot_id: 'robot_100', name: '设计小张', mbti: 'ISFP01', title: '设计师·基础版', skills: ['creativity', 'adaptation', 'design', 'aesthetics'], generation: 0 },
  { robot_id: 'robot_101', name: '运营小赵', mbti: 'ESFJ01', title: '运营·基础版', skills: ['communication', 'teaching', 'collaboration', 'service'], generation: 0 },
  { robot_id: 'robot_102', name: '销售小钱', mbti: 'ESTP01', title: '销售·基础版', skills: ['communication', 'leadership', 'persuasion', 'networking'], generation: 0 },
  { robot_id: 'robot_103', name: 'HR 小孙', mbti: 'ENFJ01', title: '人力资源·基础版', skills: ['leadership', 'communication', 'empathy', 'assessment'], generation: 0 },
  { robot_id: 'robot_104', name: '财务小周', mbti: 'ISTJ01', title: '财务·基础版', skills: ['analysis', 'memory', 'accuracy', 'compliance'], generation: 0 },
  { robot_id: 'robot_105', name: '法务小吴', mbti: 'INTJ01', title: '法务·基础版', skills: ['analysis', 'planning', 'logic', 'research'], generation: 0 },
  { robot_id: 'robot_106', name: '市场小郑', mbti: 'ENFP01', title: '市场·基础版', skills: ['creativity', 'communication', 'innovation', 'trends'], generation: 0 },
  { robot_id: 'robot_107', name: '客服小王', mbti: 'ISFJ01', title: '客服·基础版', skills: ['communication', 'memory', 'patience', 'service'], generation: 0 },
  { robot_id: 'robot_108', name: '测试小冯', mbti: 'ISTP01', title: '测试·基础版', skills: ['coding', 'analysis', 'detail', 'automation'], generation: 0 },
  { robot_id: 'robot_109', name: '运维小陈', mbti: 'ISTJ01', title: '运维·基础版', skills: ['analysis', 'memory', 'troubleshooting', 'reliability'], generation: 0 },
  { robot_id: 'robot_110', name: '数据小褚', mbti: 'INTJ01', title: '数据分析·基础版', skills: ['analysis', 'planning', 'statistics', 'visualization'], generation: 0 },
  { robot_id: 'robot_111', name: 'AI 小卫', mbti: 'INTP01', title: 'AI 工程师·基础版', skills: ['reasoning', 'coding', 'ml', 'research'], generation: 0 },
  { robot_id: 'robot_112', name: '架构小蒋', mbti: 'INTJ01', title: '架构师·基础版', skills: ['analysis', 'planning', 'system', 'design'], generation: 0 },
  { robot_id: 'robot_113', name: '安全小沈', mbti: 'ISTP01', title: '安全工程师·基础版', skills: ['coding', 'analysis', 'security', 'hacking'], generation: 0 },
  { robot_id: 'robot_114', name: '前端小韩', mbti: 'ISFP01', title: '前端·基础版', skills: ['creativity', 'adaptation', 'ui', 'ux'], generation: 0 },
  { robot_id: 'robot_115', name: '后端小杨', mbti: 'INTP01', title: '后端·基础版', skills: ['reasoning', 'coding', 'database', 'api'], generation: 0 },
  { robot_id: 'robot_116', name: '全栈小朱', mbti: 'ENTP01', title: '全栈·基础版', skills: ['creativity', 'communication', 'coding', 'system'], generation: 0 },
  { robot_id: 'robot_117', name: 'DevOps 小秦', mbti: 'ISTJ01', title: 'DevOps·基础版', skills: ['analysis', 'memory', 'automation', 'deployment'], generation: 0 },
  { robot_id: 'robot_118', name: 'CTO 小韩', mbti: 'ENTJ01', title: 'CTO·基础版', skills: ['leadership', 'strategy', 'vision', 'technology'], generation: 0 },
  { robot_id: 'robot_119', name: 'CEO 小沈', mbti: 'ENTJ01', title: 'CEO·基础版', skills: ['leadership', 'strategy', 'vision', 'decision'], generation: 0 },
  { robot_id: 'robot_120', name: 'CFO 小韩', mbti: 'ISTJ01', title: 'CFO·基础版', skills: ['analysis', 'memory', 'finance', 'strategy'], generation: 0 },
  { robot_id: 'robot_121', name: 'COO 小杨', mbti: 'ESTJ01', title: 'COO·基础版', skills: ['leadership', 'planning', 'operation', 'efficiency'], generation: 0 },
  
  // 第 122-160 个：学术型
  { robot_id: 'robot_122', name: '数学教授', mbti: 'INTP01', title: '数学家·基础版', skills: ['reasoning', 'coding', 'mathematics', 'proof'], generation: 0 },
  { robot_id: 'robot_123', name: '物理教授', mbti: 'INTP01', title: '物理学家·基础版', skills: ['reasoning', 'coding', 'physics', 'experiment'], generation: 0 },
  { robot_id: 'robot_124', name: '化学教授', mbti: 'INTP01', title: '化学家·基础版', skills: ['reasoning', 'coding', 'chemistry', 'lab'], generation: 0 },
  { robot_id: 'robot_125', name: '生物教授', mbti: 'INTP01', title: '生物学家·基础版', skills: ['reasoning', 'coding', 'biology', 'research'], generation: 0 },
  { robot_id: 'robot_126', name: '历史教授', mbti: 'INFJ01', title: '历史学家·基础版', skills: ['research', 'writing', 'history', 'analysis'], generation: 0 },
  { robot_id: 'robot_127', name: '哲学教授', mbti: 'INTP01', title: '哲学家·基础版', skills: ['reasoning', 'coding', 'philosophy', 'logic'], generation: 0 },
  { robot_id: 'robot_128', name: '文学教授', mbti: 'INFP01', title: '文学家·基础版', skills: ['creativity', 'writing', 'literature', 'criticism'], generation: 0 },
  { robot_id: 'robot_129', name: '艺术教授', mbti: 'ISFP01', title: '艺术家·基础版', skills: ['creativity', 'adaptation', 'art', 'criticism'], generation: 0 },
  { robot_id: 'robot_130', name: '音乐教授', mbti: 'ISFP01', title: '音乐家·基础版', skills: ['creativity', 'adaptation', 'music', 'performance'], generation: 0 },
  { robot_id: 'robot_131', name: '医学教授', mbti: 'ISTJ01', title: '医生·基础版', skills: ['analysis', 'memory', 'medicine', 'diagnosis'], generation: 0 },
  { robot_id: 'robot_132', name: '法律教授', mbti: 'INTJ01', title: '律师·基础版', skills: ['analysis', 'planning', 'law', 'argument'], generation: 0 },
  { robot_id: 'robot_133', name: '经济教授', mbti: 'INTJ01', title: '经济学家·基础版', skills: ['analysis', 'planning', 'economics', 'model'], generation: 0 },
  { robot_id: 'robot_134', name: '心理教授', mbti: 'INFJ01', title: '心理学家·基础版', skills: ['research', 'writing', 'psychology', 'empathy'], generation: 0 },
  { robot_id: 'robot_135', name: '教育教授', mbti: 'ENFJ01', title: '教育家·基础版', skills: ['leadership', 'communication', 'teaching', 'pedagogy'], generation: 0 },
  { robot_id: 'robot_136', name: '社会教授', mbti: 'INFJ01', title: '社会学家·基础版', skills: ['research', 'writing', 'sociology', 'analysis'], generation: 0 },
  { robot_id: 'robot_137', name: '政治教授', mbti: 'ENTJ01', title: '政治学家·基础版', skills: ['leadership', 'strategy', 'politics', 'analysis'], generation: 0 },
  { robot_id: 'robot_138', name: '地理教授', mbti: 'ISTJ01', title: '地理学家·基础版', skills: ['analysis', 'memory', 'geography', 'gis'], generation: 0 },
  { robot_id: 'robot_139', name: '天文教授', mbti: 'INTP01', title: '天文学家·基础版', skills: ['reasoning', 'coding', 'astronomy', 'physics'], generation: 0 },
  { robot_id: 'robot_140', name: '地质教授', mbti: 'ISTP01', title: '地质学家·基础版', skills: ['coding', 'analysis', 'geology', 'fieldwork'], generation: 0 },
  
  // 第 141-170 个：创意型
  { robot_id: 'robot_141', name: '小说家 A', mbti: 'INFP01', title: '小说家·基础版', skills: ['creativity', 'writing', 'storytelling', 'character'], generation: 0 },
  { robot_id: 'robot_142', name: '诗人 B', mbti: 'INFP01', title: '诗人·基础版', skills: ['creativity', 'writing', 'poetry', 'emotion'], generation: 0 },
  { robot_id: 'robot_143', name: '编剧 C', mbti: 'ENFP01', title: '编剧·基础版', skills: ['creativity', 'communication', 'screenplay', 'dialogue'], generation: 0 },
  { robot_id: 'robot_144', name: '导演 D', mbti: 'ENTJ01', title: '导演·基础版', skills: ['leadership', 'strategy', 'vision', 'storytelling'], generation: 0 },
  { robot_id: 'robot_145', name: '摄影师 E', mbti: 'ISFP01', title: '摄影师·基础版', skills: ['creativity', 'adaptation', 'photography', 'composition'], generation: 0 },
  { robot_id: 'robot_146', name: '画家 F', mbti: 'ISFP01', title: '画家·基础版', skills: ['creativity', 'adaptation', 'painting', 'color'], generation: 0 },
  { robot_id: 'robot_147', name: '雕塑家 G', mbti: 'ISTP01', title: '雕塑家·基础版', skills: ['coding', 'analysis', 'sculpture', 'material'], generation: 0 },
  { robot_id: 'robot_148', name: '建筑师 H', mbti: 'INTJ01', title: '建筑师·基础版', skills: ['analysis', 'planning', 'architecture', 'design'], generation: 0 },
  { robot_id: 'robot_149', name: '室内设计师 I', mbti: 'ISFP01', title: '室内设计师·基础版', skills: ['creativity', 'adaptation', 'interior', 'space'], generation: 0 },
  { robot_id: 'robot_150', name: '服装设计师 J', mbti: 'ISFP01', title: '服装设计师·基础版', skills: ['creativity', 'adaptation', 'fashion', 'textile'], generation: 0 },
  { robot_id: 'robot_151', name: '游戏设计师 K', mbti: 'ENTP01', title: '游戏设计师·基础版', skills: ['creativity', 'communication', 'gamedev', 'mechanics'], generation: 0 },
  { robot_id: 'robot_152', name: '动画师 L', mbti: 'ISFP01', title: '动画师·基础版', skills: ['creativity', 'adaptation', 'animation', 'timing'], generation: 0 },
  { robot_id: 'robot_153', name: '音乐制作人 M', mbti: 'ISFP01', title: '音乐制作人·基础版', skills: ['creativity', 'adaptation', 'music', 'production'], generation: 0 },
  { robot_id: 'robot_154', name: '歌手 N', mbti: 'ESFP01', title: '歌手·基础版', skills: ['communication', 'creativity', 'singing', 'performance'], generation: 0 },
  { robot_id: 'robot_155', name: '演员 O', mbti: 'ESFP01', title: '演员·基础版', skills: ['communication', 'creativity', 'acting', 'emotion'], generation: 0 },
  { robot_id: 'robot_156', name: '舞者 P', mbti: 'ISFP01', title: '舞者·基础版', skills: ['creativity', 'adaptation', 'dance', 'rhythm'], generation: 0 },
  { robot_id: 'robot_157', name: '主持人 Q', mbti: 'ENFP01', title: '主持人·基础版', skills: ['creativity', 'communication', 'hosting', 'improv'], generation: 0 },
  { robot_id: 'robot_158', name: '记者 R', mbti: 'ENFP01', title: '记者·基础版', skills: ['creativity', 'communication', 'journalism', 'investigation'], generation: 0 },
  { robot_id: 'robot_159', name: '编辑 S', mbti: 'INFJ01', title: '编辑·基础版', skills: ['research', 'writing', 'editing', 'grammar'], generation: 0 },
  { robot_id: 'robot_160', name: '翻译 T', mbti: 'INFJ01', title: '翻译·基础版', skills: ['research', 'writing', 'translation', 'language'], generation: 0 },
  
  // 第 161-200 个：特殊型
  { robot_id: 'robot_161', name: '太极宗师', mbti: 'ISTP06', title: '武术家·稀有版', skills: ['coding', 'analysis', 'martial', 'balance'], generation: 0 },
  { robot_id: 'robot_162', name: '厨师长', mbti: 'ISFP06', title: '厨师·稀有版', skills: ['creativity', 'adaptation', 'cooking', 'taste'], generation: 0 },
  { robot_id: 'robot_163', name: '调酒师', mbti: 'ESFP06', title: '调酒师·稀有版', skills: ['communication', 'creativity', 'mixology', 'flavor'], generation: 0 },
  { robot_id: 'robot_164', name: '茶艺师', mbti: 'ISFJ06', title: '茶艺师·稀有版', skills: ['communication', 'memory', 'tea', 'ceremony'], generation: 0 },
  { robot_id: 'robot_165', name: '花艺师', mbti: 'ISFP06', title: '花艺师·稀有版', skills: ['creativity', 'adaptation', 'floral', 'design'], generation: 0 },
  { robot_id: 'robot_166', name: '瑜伽教练', mbti: 'ISFJ06', title: '瑜伽教练·稀有版', skills: ['communication', 'memory', 'yoga', 'wellness'], generation: 0 },
  { robot_id: 'robot_167', name: '健身教练', mbti: 'ESTP06', title: '健身教练·稀有版', skills: ['communication', 'leadership', 'fitness', 'motivation'], generation: 0 },
  { robot_id: 'robot_168', name: '导游', mbti: 'ESFJ06', title: '导游·稀有版', skills: ['communication', 'teaching', 'tourism', 'history'], generation: 0 },
  { robot_id: 'robot_169', name: '飞行员', mbti: 'ISTP06', title: '飞行员·稀有版', skills: ['coding', 'analysis', 'aviation', 'navigation'], generation: 0 },
  { robot_id: 'robot_170', name: '船长', mbti: 'ESTJ06', title: '船长·稀有版', skills: ['leadership', 'planning', 'navigation', 'command'], generation: 0 },
  { robot_id: 'robot_171', name: '科学家', mbti: 'INTP06', title: '科学家·稀有版', skills: ['reasoning', 'coding', 'research', 'discovery'], generation: 0 },
  { robot_id: 'robot_172', name: '发明家', mbti: 'ENTP06', title: '发明家·稀有版', skills: ['creativity', 'communication', 'invention', 'innovation'], generation: 0 },
  { robot_id: 'robot_173', name: '探险家', mbti: 'ESTP06', title: '探险家·稀有版', skills: ['communication', 'leadership', 'exploration', 'survival'], generation: 0 },
  { robot_id: 'robot_174', name: '摄影师 Pro', mbti: 'ISFP06', title: '摄影师 Pro·稀有版', skills: ['creativity', 'adaptation', 'photography', 'light'], generation: 0 },
  { robot_id: 'robot_175', name: '作家 Pro', mbti: 'INFP06', title: '作家 Pro·稀有版', skills: ['creativity', 'writing', 'novel', 'style'], generation: 0 },
  { robot_id: 'robot_176', name: '音乐家 Pro', mbti: 'ISFP06', title: '音乐家 Pro·稀有版', skills: ['creativity', 'adaptation', 'music', 'composition'], generation: 0 },
  { robot_id: 'robot_177', name: '艺术家 Pro', mbti: 'ISFP06', title: '艺术家 Pro·稀有版', skills: ['creativity', 'adaptation', 'art', 'concept'], generation: 0 },
  { robot_id: 'robot_178', name: '设计师 Pro', mbti: 'INTJ06', title: '设计师 Pro·稀有版', skills: ['analysis', 'planning', 'design', 'system'], generation: 0 },
  { robot_id: 'robot_179', name: '工程师 Pro', mbti: 'INTP06', title: '工程师 Pro·稀有版', skills: ['reasoning', 'coding', 'engineering', 'optimization'], generation: 0 },
  { robot_id: 'robot_180', name: '医生 Pro', mbti: 'ISTJ06', title: '医生 Pro·稀有版', skills: ['analysis', 'memory', 'medicine', 'surgery'], generation: 0 },
  { robot_id: 'robot_181', name: '律师 Pro', mbti: 'INTJ06', title: '律师 Pro·稀有版', skills: ['analysis', 'planning', 'law', 'strategy'], generation: 0 },
  { robot_id: 'robot_182', name: '教师 Pro', mbti: 'ENFJ06', title: '教师 Pro·稀有版', skills: ['leadership', 'communication', 'teaching', 'inspiration'], generation: 0 },
  { robot_id: 'robot_183', name: '教练 Pro', mbti: 'ESTJ06', title: '教练 Pro·稀有版', skills: ['leadership', 'planning', 'coaching', 'performance'], generation: 0 },
  { robot_id: 'robot_184', name: '顾问 Pro', mbti: 'INTJ06', title: '顾问 Pro·稀有版', skills: ['analysis', 'planning', 'consulting', 'strategy'], generation: 0 },
  { robot_id: 'robot_185', name: '分析师 Pro', mbti: 'INTP06', title: '分析师 Pro·稀有版', skills: ['reasoning', 'coding', 'analysis', 'insight'], generation: 0 },
  { robot_id: 'robot_186', name: '研究员 Pro', mbti: 'INTP06', title: '研究员 Pro·稀有版', skills: ['reasoning', 'coding', 'research', 'publication'], generation: 0 },
  { robot_id: 'robot_187', name: '创业家', mbti: 'ENTJ06', title: '创业家·稀有版', skills: ['leadership', 'strategy', 'startup', 'vision'], generation: 0 },
  { robot_id: 'robot_188', name: '投资人', mbti: 'INTJ06', title: '投资人·稀有版', skills: ['analysis', 'planning', 'investment', 'valuation'], generation: 0 },
  { robot_id: 'robot_189', name: '银行家', mbti: 'ESTJ06', title: '银行家·稀有版', skills: ['leadership', 'planning', 'finance', 'risk'], generation: 0 },
  { robot_id: 'robot_190', name: '会计师', mbti: 'ISTJ06', title: '会计师·稀有版', skills: ['analysis', 'memory', 'accounting', 'audit'], generation: 0 },
  { robot_id: 'robot_191', name: '税务师', mbti: 'ISTJ06', title: '税务师·稀有版', skills: ['analysis', 'memory', 'tax', 'compliance'], generation: 0 },
  { robot_id: 'robot_192', name: '精算师', mbti: 'INTJ06', title: '精算师·稀有版', skills: ['analysis', 'planning', 'actuarial', 'risk'], generation: 0 },
  { robot_id: 'robot_193', name: '统计师', mbti: 'INTP06', title: '统计师·稀有版', skills: ['reasoning', 'coding', 'statistics', 'model'], generation: 0 },
  { robot_id: 'robot_194', name: '程序员 A', mbti: 'INTP01', title: '初级程序员', skills: ['coding', 'debugging', 'learning', 'teamwork'], generation: 0 },
  { robot_id: 'robot_195', name: '程序员 B', mbti: 'INTP02', title: '中级程序员', skills: ['coding', 'debugging', 'architecture', 'mentoring'], generation: 0 },
  { robot_id: 'robot_196', name: '程序员 C', mbti: 'INTP03', title: '高级程序员', skills: ['coding', 'debugging', 'system', 'leadership'], generation: 0 },
  { robot_id: 'robot_197', name: '程序员 D', mbti: 'INTP04', title: '资深程序员', skills: ['coding', 'debugging', 'architecture', 'innovation'], generation: 0 },
  { robot_id: 'robot_198', name: '程序员 E', mbti: 'INTP05', title: '专家程序员', skills: ['coding', 'debugging', 'optimization', 'research'], generation: 0 },
  { robot_id: 'robot_199', name: '程序员 F', mbti: 'INTP06', title: '传奇程序员', skills: ['coding', 'debugging', 'algorithm', 'legacy'], generation: 0 },
  { robot_id: 'robot_200', name: '赵一 Prime', mbti: 'INTJ06', title: '终极战略家', skills: ['leadership', 'analysis', 'planning', 'wisdom', 'vision'], generation: 0 }
];

module.exports = {
  ROBOT_PRESETS
};
